# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# 

SUPER_TYPES = ["Basic", "Legendary", "World", "Snow"]
CARD_TYPES = ["Planeswalker", "Tribal", "Instant", "Sorcery", "Artifact", "Land", "Enchantment", "Creature"]
COLORS = ["White", "Blue", "Black", "Red", "Green"]
COLOR_IMGS = [
	"https://s3.amazonaws.com/decksterdev/defaults/Mana_W.png",
	"https://s3.amazonaws.com/decksterdev/defaults/Mana_U+(1).png",
	"https://s3.amazonaws.com/decksterdev/defaults/Mana_B.png",
	"https://s3.amazonaws.com/decksterdev/defaults/Mana_R.png",
	"https://s3.amazonaws.com/decksterdev/defaults/Mana_G.png"
]

SUPER_TYPES.each do |type|
	SuperType.create!({name: type})
end

CARD_TYPES.each do |type|
	CardType.create!({name: type})
end

COLORS.each_with_index do |color, idx|
	abbrv = color == "Blue" ? "U" : color[0]
	Color.create!({name: color, abbreviation: abbrv, image: COLOR_IMGS[idx]})
end

# Guest User

guest_user = User.create({
	username: "Guest",
	email: "test@test.test",
	password_digest: BCrypt::Password.create("guestlogin"),
	session_token: SecureRandom.urlsafe_base64
})

profile = Profile.create({
	user_id: guest_user.id,
	bio: "DIS DONC JEAN PAUL"
})

decks = [Deck.create({
		profile_id: profile.id,
		title: "Dredge",
		description: "",
		key_card: "Bridge from Below"
	}),
	Deck.create({
		profile_id: profile.id,
		title: "Doomsday",
		description: "",
		key_card: "Doomsday"
	})]

dredge = decks[0]
dredge_cards = Card.create([{
	deck_id: dredge.id,
	name: "Bridge from Below",
	mana_cost: "BBB",
	cmc: 3,
	text: "Whenever a nontoken creature is put into your graveyard from the battlefield, if Bridge from Below is in your graveyard, put a 2/2 black Zombie creature token onto the battlefield. When a creature is put into an opponent's graveyard from the battlefield, if Bridge from Below is in your graveyard, exile Bridge from Below.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/136054.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Flame-kin Zealot",
	mana_cost: "1RRW",
	cmc: 4,
	text: "When Flame-Kin Zealot enters the battlefield, creatures you control get +1/+1 and gain haste until end of turn.",
	power: "2",
	toughness: "2",
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/83562.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: dredge.id,
	name: "Golgari Grave-Troll",
	mana_cost: "4G",
	cmc: 5,
	text: "Golgari Grave-Troll enters the battlefield with a +1/+1 counter on it for each creature card in your graveyard. {1}, Remove a +1/+1 counter from Golgari Grave-Troll: Regenerate Golgari Grave-Troll. Dredge 6 (If you would draw a card, instead you may put exactly six cards from the top of your library into your graveyard. If you do, return this card from your graveyard to your hand. Otherwise, draw a card.)",
	power: "0",
	toughness: "0",
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/88960.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Golgari Thug",
	mana_cost: "1B",
	cmc: 2,
	text: "When Golgari Thug dies, put target creature card from your graveyard on top of your library. Dredge 4 (If you would draw a card, instead you may put exactly four cards from the top of your library into your graveyard. If you do, return this card from your graveyard to your hand. Otherwise, draw a card.)",
	power: "1",
	toughness: "1",
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/88994.jpg",
	loyalty: nil,
	quantity: 2,
}, {
	deck_id: dredge.id,
	name: "Ichorid",
	mana_cost: "3B",
	cmc: 4,
	text: "Haste At the beginning of the end step, sacrifice Ichorid. At the beginning of your upkeep, if Ichorid is in your graveyard, you may exile a black creature card other than Ichorid from your graveyard. If you do, return Ichorid to the battlefield.",
	power: "3",
	toughness: "1",
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/35923.jpg",
	loyalty: nil,
	quantity: 3,
}, {
	deck_id: dredge.id,
	name: "Iona, Shield of Emeria",
	mana_cost: "6WWW",
	cmc: 9,
	text: "Flying As Iona, Shield of Emeria enters the battlefield, choose a color. Your opponents can't cast spells of the chosen color.",
	power: "7",
	toughness: "7",
	rarity: "Mythic",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/190407.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: dredge.id,
	name: "Narcomoeba",
	mana_cost: "1U",
	cmc: 2,
	text: "Flying When Narcomoeba is put into your graveyard from your library, you may put it onto the battlefield.",
	power: "1",
	toughness: "1",
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/136140.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Putrid Imp",
	mana_cost: "B",
	cmc: 1,
	text: "Discard a card: Putrid Imp gains flying until end of turn. Threshold — As long as seven or more cards are in your graveyard, Putrid Imp gets +1/+1 and can't block.",
	power: "1",
	toughness: "1",
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/34470.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Sphinx of Lost Truths",
	mana_cost: "3UU",
	cmc: 5,
	text: "Kicker {1}{U} (You may pay an additional {1}{U} as you cast this spell.) Flying When Sphinx of Lost Truths enters the battlefield, draw three cards. Then if it wasn't kicked, discard three cards.",
	power: "3",
	toughness: "5",
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/185751.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: dredge.id,
	name: "Stinkweed Imp",
	mana_cost: "2B",
	cmc: 3,
	text: "Flying Whenever Stinkweed Imp deals combat damage to a creature, destroy that creature. Dredge 5 (If you would draw a card, instead you may put exactly five cards from the top of your library into your graveyard. If you do, return this card from your graveyard to your hand. Otherwise, draw a card.)",
	power: "1",
	toughness: "2",
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/87984.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Tireless Tribe",
	mana_cost: "W",
	cmc: 1,
	text: "Discard a card: Tireless Tribe gets +0/+4 until end of turn.",
	power: "1",
	toughness: "1",
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/29695.jpg",
	loyalty: nil,
	quantity: 3,
}, {
	deck_id: dredge.id,
	name: "Breakthrough",
	mana_cost: "XU",
	cmc: 1,
	text: "Draw four cards, then choose X cards in your hand and discard the rest.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/29927.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Cabal Therapy",
	mana_cost: "B",
	cmc: 1,
	text: "Name a nonland card. Target player reveals his or her hand and discards all cards with that name. Flashback—Sacrifice a creature. (You may cast this card from your graveyard for its flashback cost. Then exile it.)",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/34789.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Careful Study",
	mana_cost: "U",
	cmc: 1,
	text: "Draw two cards, then discard two cards.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/29727.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: dredge.id,
	name: "Dread Return",
	mana_cost: "2BB",
	cmc: 4,
	text: "Return target creature card from your graveyard to the battlefield. Flashback—Sacrifice three creatures. (You may cast this card from your graveyard for its flashback cost. Then exile it.)",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/116721.jpg",
	loyalty: nil,
	quantity: 2,
}, {
	deck_id: dredge.id,
	name: "Faithless Looting",
	mana_cost: "R",
	cmc: 1,
	text: "Draw two cards, then discard two cards. Flashback {2}{R} (You may cast this card from your graveyard for its flashback cost. Then exile it.)",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/245299.jpg",
	loyalty: nil,
	quantity: 3,
}, {
	deck_id: dredge.id,
	name: "Cephalid Coliseum",
	mana_cost: "",
	cmc: 0,
	text: "{T}: Add {U} to your mana pool. Cephalid Coliseum deals 1 damage to you. Threshold — {U}, {T}, Sacrifice Cephalid Coliseum: Target player draws three cards, then discards three cards. Activate this ability only if seven or more cards are in your graveyard.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/29903.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Gemstone Mine",
	mana_cost: "",
	cmc: 0,
	text: "Gemstone Mine enters the battlefield with three mining counters on it. {T}, Remove a mining counter from Gemstone Mine: Add one mana of any color to your mana pool. If there are no mining counters on Gemstone Mine, sacrifice it.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/4592.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Mana Confluence",
	mana_cost: "",
	cmc: 0,
	text: "{T}, Pay 1 life: Add one mana of any color to your mana pool.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/380453.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: dredge.id,
	name: "Undiscovered Paradise",
	mana_cost: "",
	cmc: 0,
	text: "{T}: Add one mana of any color to your mana pool. During your next untap step, as you untap your permanents, return Undiscovered Paradise to its owner's hand.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/3755.jpg",
	loyalty: nil,
	quantity: 3,
}])

doomsday = decks[1]
doomsday_cards = Card.create([{
	deck_id: doomsday.id,
	name: "Badlands",
	mana_cost: "",
	cmc: 0,
	text: "({T}: Add {B} or {R} to your mana pool.)",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/279.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Bloodstained Mire",
	mana_cost: "",
	cmc: 0,
	text: "{T}, Pay 1 life, Sacrifice Bloodstained Mire: Search your library for a Swamp or Mountain card and put it onto the battlefield. Then shuffle your library.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/39505.jpg",
	loyalty: nil,
	quantity: 2,
}, {
	deck_id: doomsday.id,
	name: "Island",
	mana_cost: "",
	cmc: 0,
	text: "",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/73951.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Karakas",
	mana_cost: "",
	cmc: 0,
	text: "{T}: Add {W} to your mana pool. {T}: Return target legendary creature to its owner's hand.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/1701.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Polluted Delta",
	mana_cost: "",
	cmc: 0,
	text: "{T}, Pay 1 life, Sacrifice Polluted Delta: Search your library for an Island or Swamp card and put it onto the battlefield. Then shuffle your library.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/39504.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Scalding Tarn",
	mana_cost: "",
	cmc: 0,
	text: "{T}, Pay 1 life, Sacrifice Scalding Tarn: Search your library for an Island or Mountain card and put it onto the battlefield. Then shuffle your library.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/190393.jpg",
	loyalty: nil,
	quantity: 3,
}, {
	deck_id: doomsday.id,
	name: "Swamp",
	mana_cost: "",
	cmc: 0,
	text: "",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/73973.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Underground Sea",
	mana_cost: "",
	cmc: 0,
	text: "({T}: Add {U} or {B} to your mana pool.)",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/287.jpg",
	loyalty: nil,
	quantity: 2,
}, {
	deck_id: doomsday.id,
	name: "Volcanic Island",
	mana_cost: "",
	cmc: 0,
	text: "({T}: Add {U} or {R} to your mana pool.)",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/585.jpg",
	loyalty: nil,
	quantity: 2,
}, {
	deck_id: doomsday.id,
	name: "Brainstorm",
	mana_cost: "U",
	cmc: 1,
	text: "Draw three cards, then put two cards from your hand on top of your library in any order.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/19571.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Burning Wish",
	mana_cost: "1R",
	cmc: 2,
	text: "You may choose a sorcery card you own from outside the game, reveal that card, and put it into your hand. Exile Burning Wish.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/34403.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Cabal Therapy",
	mana_cost: "B",
	cmc: 1,
	text: "Name a nonland card. Target player reveals his or her hand and discards all cards with that name. Flashback—Sacrifice a creature. (You may cast this card from your graveyard for its flashback cost. Then exile it.)",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/34789.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Chain of Vapor",
	mana_cost: "U",
	cmc: 1,
	text: "Return target nonland permanent to its owner's hand. Then that permanent's controller may sacrifice a land. If the player does, he or she may copy this spell and may choose a new target for that copy.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/12447.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Dark Ritual",
	mana_cost: "B",
	cmc: 1,
	text: "Add {B}{B}{B} to your mana pool.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/651.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Doomsday",
	mana_cost: "BBB",
	cmc: 3,
	text: "Search your library and graveyard for five cards and exile the rest. Put the chosen cards on top of your library in any order. You lose half your life, rounded up.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/4454.jpg",
	loyalty: nil,
	quantity: 3,
}, {
	deck_id: doomsday.id,
	name: "Duress",
	mana_cost: "B",
	cmc: 1,
	text: "Target opponent reveals his or her hand. You choose a noncreature, nonland card from it. That player discards that card.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/5557.jpg",
	loyalty: nil,
	quantity: 3,
}, {
	deck_id: doomsday.id,
	name: "Gitaxian Probe",
	mana_cost: "{U/P}",
	cmc: 1,
	text: "({U/P} can be paid with either {U} or 2 life.) Look at target player's hand. Draw a card.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/233056.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Ideas Unbound",
	mana_cost: "UU",
	cmc: 2,
	text: "Draw three cards. Discard three cards at the beginning of the next end step.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/88789.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Ponder",
	mana_cost: "U",
	cmc: 1,
	text: "Look at the top three cards of your library, then put them back in any order. You may shuffle your library. Draw a card.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/139512.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Rain of Filth",
	mana_cost: "B",
	cmc: 1,
	text: "Until end of turn, lands you control gain 'Sacrifice this land: Add {B} to your mana pool.'",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/5831.jpg",
	loyalty: nil,
	quantity: 1,
}, {
	deck_id: doomsday.id,
	name: "Lion's Eye Diamond",
	mana_cost: "0",
	cmc: 0,
	text: "Sacrifice Lion's Eye Diamond, Discard your hand: Add three mana of any one color to your mana pool. Activate this ability only any time you could cast an instant.",
	power: nil,
	toughness: nil,
	rarity: "Rare",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/3255.jpg",
	loyalty: nil,
	quantity: 4,
}, {
	deck_id: doomsday.id,
	name: "Lotus Petal",
	mana_cost: "0",
	cmc: 0,
	text: "{T}, Sacrifice Lotus Petal: Add one mana of any color to your mana pool.",
	power: nil,
	toughness: nil,
	rarity: "Common",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/4614.jpg",
	loyalty: nil,
	quantity: 2,
}, {
	deck_id: doomsday.id,
	name: "Sensei's Divining Top",
	mana_cost: "1",
	cmc: 1,
	text: "{1}: Look at the top three cards of your library, then put them back in any order. {T}: Draw a card, then put Sensei's Divining Top on top of its owner's library.",
	power: nil,
	toughness: nil,
	rarity: "Uncommon",
	edition: nil,
	foil: false,
	image_url: "https://image.deckbrew.com/mtg/multiverseid/50400.jpg",
	loyalty: nil,
	quantity: 4,
}])